### ISSUE TITLE
Apply to be Razer Phone (cheryl) official maintainer

### ISSUE THREAD

**Issue by KaguraRinko** [TeamWin/android_bootable_recovery#100]
Hi TWRP team.
I'm Baolong Wu (baolong24), an Android Enthusiast.
I have a Razer Phone.
When i flash the TWRP at TWRP official website,i found the official TWRP is buggy.
For now the official TWRP for Razer Phone can't flash ROM in,can't decrypt, MTP not working, etc.
But I fixed the issues, I rebuild the TWRP device tree and it's working fine, many issues has been fixed.
In my own TWRP build, MTP/ADB/USB is working, data decrypt is also working, ROM also can flash in now.

Here's my TWRP device tree: [https://github.com/baolong24/android_device_razer_cheryl/tree/twrp-9.0](https://github.com/baolong24/android_device_razer_cheryl/tree/twrp-9.0)
I hope TWRP team could merge it to official GitHub repositoriy, So that more and more people can use the no buggy TWRP.

**Comment by bigbiff** [comment]
Hello, thanks for your interest in maintaining cheryl. I have setup a jenkins job. Can you test https://build.twrp.me/twrp-3.5.0_9-0-cheryl.img

**Comment by KaguraRinko** [comment]
> Hello, thanks for your interest in maintaining cheryl. I have setup a jenkins job. Can you test https://build.twrp.me/twrp-3.5.0_9-0-cheryl.img

Hello, I'm sorry for that, I forget to define TARGET_RECOVERY_FSTAB, so this build can't flash rom, but everything working fine without flash in this build.

But I has been define TARGET_RECOVERY_FSTAB for now, so I build a new one, now everything working fine in my build.
[https://github.com/baolong24/android_device_razer_cheryl/commit/721276f9e555334a1f271f9d3e6438df07412d56](https://github.com/baolong24/android_device_razer_cheryl/commit/721276f9e555334a1f271f9d3e6438df07412d56)

Could you build new one to give me test?

**Comment by bigbiff** [comment]
I pulled changes and reran the build. Please test https://build.twrp.me/twrp-3.5.0_9-0-cheryl.img

**Comment by KaguraRinko** [comment]
> I pulled changes and reran the build. Please test https://build.twrp.me/twrp-3.5.0_9-0-cheryl.img

Hi, Thanks for your build, I tested. Now everything working fine and well

**Comment by bigbiff** [comment]
Thanks for testing. Would you be able to update the twrpme device markdown to your username on gerrit.twrp.me?

**Comment by KaguraRinko** [comment]
> Thanks for testing. Would you be able to update the twrpme device markdown to your username on gerrit.twrp.me?

Of course. But how can I push the change to gerrit.twrp.me?

```shell
baolong24s-MacBook-Pro:twrpme baolong24$ git push origin master
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 8 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 373 bytes | 373.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3)
remote: error: branch refs/heads/master:
remote: To push into this reference you need 'Push' rights.
remote: User: baolong24
remote: Contact an administrator to fix the permissions
remote: Processing changes: refs: 1, done    
To ssh://gerrit.twrp.me:29418/twrpme
 ! [remote rejected] master -> master (prohibited by Gerrit: not permitted: update)
error: failed to push some refs to 'ssh://baolong24@gerrit.twrp.me:29418/twrpme'
```

**Comment by bigbiff** [comment]
Please use the command
git push origin HEAD:refs/for/master

**Comment by KaguraRinko** [comment]
> Please use the command
> git push origin HEAD:refs/for/master

Thanks, I pushed now
[https://gerrit.twrp.me/c/twrpme/+/3223](https://gerrit.twrp.me/c/twrpme/+/3223)
