### ISSUE TITLE
3.5.1_9-0 on gemini: crashing after splash screen

### ISSUE THREAD

**Issue by DinoBrdar92** [TeamWin/android_bootable_recovery#129]
- [ yes] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ yes] I am running the latest version of TWRP
- [ not really] I have read the FAQ (https://twrp.me/FAQ/)
- [ will do] I have searched for my issue and it does not already exist

**Device codename**: gemini
**TWRP version**: 3.5.1_9-0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Trying to enter recovery.

#### WHAT IS THE EXPECTED RESULT?
It should enter the TWRP recovery.

#### WHAT HAPPENS INSTEAD?
It just shows splash screen, and then after 1-2 seconds the phone restarts.

#### ADDITIONAL INFORMATION
I tried downloading 2 different .IMG files 2 different times to avoid the possibility of corrupted file, and I tried updating it once through both recovery and second time through Official TWRP App, but both times the same thing happened.

`/tmp/recovery.log`: 
`dmesg`: 
Regarding recovery logs, I reverted back to 3.5.0_9-0 immediately after realising it's broken, and I couldn't locate /tmp/recovery.log on my phone. If I do, I'll edit it in.

**Comment by luk1337** [comment]
@DinoBrdar92 3.5.1_9.0 for this device has been rebuilt last night, please try the new build.

**Comment by DinoBrdar92** [comment]
@luk1337 Tried the new build and it enters recovery normally now, so the problem is resolved!
