### ISSUE TITLE
Doogee s88 pro : TWRP REQUEST !

### ISSUE THREAD

**Issue by Cougar16** [TeamWin/android_bootable_recovery#152]
Hi TWRP TEAM ,
I hope you are doing well 🙂 , Doogee company has become one of the most popular companies in producing smartphones in the worldwide, please can you build one for this device DOOGEE S88 PRO ? I will really appreciate your help if you can build one for this device ! I can provide you the stock recovery if needed ! Thank you to reply in advance 🙂 
BEST regards to you @TeamWin-Gerrit

**Comment by bigbiff** [comment]
Please don't open device requests here.

**Comment by beedell-roke** [comment]
@bigbiff, where should support for new devices be requested?
