### ISSUE TITLE
TWRP 

### ISSUE THREAD

**Issue by Nadzkielegit** [TeamWin/android_bootable_recovery#178]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: 
**TWRP version**: 

#### ADDITIONAL INFORMATION

`/tmp/recovery.log`: 
`dmesg`:

**Comment by Nadzkielegit** [comment]
/tmp/recovery.log:
dmesg:

**Comment by beedell-roke** [comment]
@ronaldinzkie, do you require assistance to upload the file?
