### ISSUE TITLE
Twrp for POCO X2 (PhoenixIN)

### ISSUE THREAD

**Issue by sandirickyroy** [TeamWin/android_bootable_recovery#25]
I request you to consider releasing TWRP for POCO X2 (PhoenixIN) as it's been more than 5 months since its release date.
Please please please 🙏🙏🙏

**Comment by mauronofrio** [comment]
It will be released in the next months

**Comment by sandirickyroy** [comment]
> ce. We're all eagerly waiting for it...

**Comment by sandirickyroy** [comment]
> It will be released in the next months

Thanks in advance. We're all eagerly waiting for it.

**Comment by Terrorysta** [comment]
I am learnig

**Comment by Terrorysta** [comment]
> > It will be released in the next months
> 
> Thanks in advance. We're all eagerly waiting for it.

**Comment by Terrorysta** [comment]
> I request you to consider releasing TWRP for POCO X2 (PhoenixIN) as it's been more than 5 months since its release date.
> Please please please 🙏🙏🙏

**Comment by bigbiff** [comment]
Don't open up device requests as issues.
