### ISSUE TITLE
Please make a TWRP for pissarro (redemi Note 11Pro / Pro+) 

### ISSUE THREAD

**Issue by MYSK-QC** [TeamWin/android_bootable_recovery#258]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [ ] I have read the FAQ (https://twrp.me/FAQ/)
- [ ] I have searched for my issue and it does not already exist

**Device codename**: 
**TWRP version**: 

#### ADDITIONAL INFORMATION

`/tmp/recovery.log`: 
`dmesg`:

**Comment by ShyVaporeon** [comment]
I am also waiting for this.
