### ISSUE TITLE
Version 3.7.0 is too large to flash on hero2lte (Samsung Galaxy S7 Edge SM-G935F)

### ISSUE THREAD

**Issue by igormmartins** [TeamWin/android_bootable_recovery#270]
- [ x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ ] I am running the latest version of TWRP
- [x ] I have read the FAQ (https://twrp.me/FAQ/)
- [x ] I have searched for my issue and it does not already exist

hero2lte: 
3.6.1: 

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Try flash the new versoin to the phone through TWRP 3.6.1, TWRP official app or jodin.

#### WHAT IS THE EXPECTED RESULT?
Get it to flash, as follows in the log

[IMAGE FLASH STARTED]
Image to flash: '/external_sd/twrp-3.6.1_9-0-hero2lte.img'
Calculating restore details...
I:Image filename is: twrp-3.6.1_9-0-hero2lte.img
I:Reading '/external_sd/twrp-3.6.1_9-0-hero2lte.img', writing '/dev/block/platform/155a0000.ufs/by-name/RECOVERY'
[IMAGE FLASH COMPLETED]

#### WHAT HAPPENS INSTEAD?
Tells file "is larger than target device" as follows in the log

[IMAGE FLASH STARTED]
Image to flash: '/external_sd/twrp-3.7.0_9-0-hero2lte.img'
Calculating restore details...
I:Image filename is: twrp-3.7.0_9-0-hero2lte.img
I:Size (49035280 bytes) of image 'twrp-3.7.0_9-0-hero2lte.img' is larger than target device '/dev/block/platform/155a0000.ufs/by-name/RECOVERY' (48234496 bytes)
Size of image is larger than target device

#### ADDITIONAL INFORMATION
Writing the img from the official app resulted in a bootloop. The jodin program ended in the same result. Although both methods worked with the older version of TWRP.

paste.omnirom.org isn't working, using pastebin instead

`/tmp/recovery.log`: https://pastebin.com/2XefcmKg
`dmesg`:  too large to fit, file attached below
[dmesg.txt](https://github.com/TeamWin/android_bootable_recovery/files/9781299/dmesg.txt)

**Comment by comrade-meowski** [comment]
I can confirm the same issue on Samsung S7 G930F "herolte" with twrp-3.7.0_9-0-hero2lte.img.

Reflashing the previous twrp-3.6.2_9-0-herolte.img via the twrp app or via heimdall restores normal operation.

**Comment by Gartux** [comment]
I can confirm the same issue too !

**Comment by Dusk-Golem** [comment]
I have the same issue, "size of image is larger than target device" but on Galaxy A8 2018 Android 9.0 Stock Rom. twrp 3.6.2_9.0 still works fine.

**Comment by gh2011** [comment]
I had the same problem also with the non-Edge version of the Galaxy S7 G930F (herolte). I tried flashing the TWRP tar file with Odin, and that didn't work either, Odin just gave me a vague Failed message.

**Comment by igormmartins** [comment]
Get my hands on another device, same model and stock, tried to flash it through jodin and got the same error as the other device:

"Uploading RECOVERY
100%
ERROR: Failed to confirm end of file transfer sequence!
ERROR: RECOVERY upload failed!"

**Comment by comrade-meowski** [comment]
I've found the same issue with TWRP 3.7.0 on multiple different Samsungs since then so it's apparently a general mistake.

It's pretty safe for us to assume at this point that the devs don't read their own github issues either so this clearly isn't getting addressed any time soon ¯\\_(ツ)_/¯

**Comment by SandraEickel** [comment]
Issue #288 seems to be similar - I don't recall if there was such an error message, but my Samsung Galaxy S5 Neo LTE (s5neolte) and other models like a3xelte and a5xelte don't boot after flashing 3.7.0_9-0 while the previous version 3.6.2_9-0 works as expected, so the range of affected Samsung phones grows further, even if @comrade-meowski didn't specify those devices.

**Comment by TAbdiukov** [comment]
Was about to write about (seemingly) the same issue

Environment: hero2lte + Odin3_v3.14.4

TWRP 3.7.0 (tried both .tar and .img.tar) -FAIL x2
```
<ID:0/008> Added!!
<ID:0/008> Odin engine v(ID:3.1401)..
<ID:0/008> File analysis..
<ID:0/008> Total Binary size: 46 M
<ID:0/008> SetupConnection..
<ID:0/008> Initialzation..
<ID:0/008> Get PIT for mapping..
<ID:0/008> Firmware update start..
<ID:0/008> NAND Write Start!! 
<ID:0/008> SingleDownload.
<ID:0/008> recovery.img
<ID:0/008> FAIL!
<ID:0/008> 
<ID:0/008> Complete(Write) operation failed.
<OSM> All threads completed. (succeed 0 / failed 1)
<ID:0/008> Odin engine v(ID:3.1401)..
<ID:0/008> File analysis..
<ID:0/008> Total Binary size: 46 M
<ID:0/008> SetupConnection..
<ID:0/008> Removed!!
<ID:0/008> Initialzation..
<ID:0/008> Get PIT for mapping..
<ID:0/008> Firmware update start..
<ID:0/008> NAND Write Start!! 
<ID:0/008> SingleDownload.
<ID:0/008> recovery.img
<ID:0/008> FAIL!
<ID:0/008> 
<ID:0/008> Complete(Write) operation failed.
<OSM> All threads completed. (succeed 0 / failed 1)
```

TWRP v3.6.2 (.tar) - SUCCESS
```
<ID:0/008> Added!!
<ID:0/008> Odin engine v(ID:3.1401)..
<ID:0/008> File analysis..
<ID:0/008> Total Binary size: 44 M
<ID:0/008> SetupConnection..
<ID:0/008> Initialzation..
<ID:0/008> Get PIT for mapping..
<ID:0/008> Firmware update start..
<ID:0/008> NAND Write Start!! 
<ID:0/008> SingleDownload.
<ID:0/008> recovery.img
<ID:0/008> RQT_CLOSE !!
<ID:0/008> RES OK !!
<ID:0/008> Removed!!
<ID:0/008> Remain Port ....  0 
<OSM> All threads completed. (succeed 1 / failed 0)
```

**Comment by igormmartins** [comment]
Version 3.7.0_9-1 fixed this issue for hero2lte.
Although this version has no android 12 encryption support, verified when trying to decrypt by terminal.

**Comment by IIIPTR** [comment]
Wysłane z aplikacji Poczta dla systemu Windows  Od: igormmartinsWysłano: niedziela, 27 sierpnia 2023 02:24Do: TeamWin/android_bootable_recoveryDW: SubscribedTemat: Re: [TeamWin/android_bootable_recovery] Version 3.7.0 is too large to flash on hero2lte (Samsung Galaxy S7 Edge SM-G935F) (Issue #270) Version 3.7.0_9-1 fixed this issue for hero2lte.Although this version has no android 12 encryption support, verified when trying to decrypt by terminal.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by g6094199** [comment]
>  Samsung Galaxy S5 Neo LTE (s5neolte)

+1

doesnt bot with twrp-3.7.0_9-0-s5neolte.img
