### ISSUE TITLE
NEED TWRP REALME C3 RMX2020

### ISSUE THREAD

**Issue by sunnyvirus** [TeamWin/android_bootable_recovery#35]
i need plz twrp of realme c3 
plz make twrp of realme c3

**Comment by djdelarosa25** [comment]
Please close this.

**Comment by bigbiff** [comment]
Don't open device requests as issues.

**Comment by mehedihassan4111** [comment]
I need to realme c3 TWRP recovery
Please make a TWRP recovery for realme c3 Rmx 2020

**Comment by djdelarosa25** [comment]
> I need to realme c3 TWRP recovery
> Please make a TWRP recovery for realme c3 Rmx 2020

Shut the fuck up.

**Comment by mehedihassan4111** [comment]
> > I need to realme c3 TWRP recovery
> > Please make a TWRP recovery for realme c3 Rmx 2020
> 
> Shut the fuck up.

Why,,??
