### ISSUE TITLE
Need TWRP for my ASUS ZenPad 8.0 (Z380KL) 

### ISSUE THREAD

**Issue by TroubledG** [TeamWin/android_bootable_recovery#36]
Please help,

i can't find it in Teamwin website under - TWRP oem devices for Asus Zenpad 8.0 ( Z380KL ).
Do advise further any other place i can download.

Warm regards,
TroubledG

**Comment by djdelarosa25** [comment]
Please close this.

**Comment by bigbiff** [comment]
Don't open issues for device requests.
