### ISSUE TITLE
Bug regarding fs_mgr library

### ISSUE THREAD

**Issue by Galax1eo** [TeamWin/android_bootable_recovery#366]
**Device codename**: m31s
**TWRP version**: 3.7.1
**TWRP Official Build**: https://twrp.me/samsung/samsunggalaxym31s.html
**TWRP Tree**: https://github.com/TeamWin/android_device_samsung_m31s

#### Explain your issue properly?
So, the thing is, i was deleting file in system from twrp and it wasn't deleting and gave error
```
I:Running command: 'rm -rf "/system_root/system/test.delete"'                                   rm: /system_root/system/test.delete: Read-only file system
```
After checking logs, i got to know that /system_root wasn't getting mount

But when i tried to mount from terminal and then tried to delete the file, it was working
```
[   35.980664] EXT4-fs (dm-0): mounted filesystem without journal. Opts: barrier=1,discard
```
I took the help of a dev and he said that he don't think it's tree related bug
It's bug of fs_mgr library of android source code
So yeah sources and twrp sources bug

`/tmp/recovery.log`: 
`dmesg`: 

[dmesg.log](https://github.com/user-attachments/files/16574190/dmesg.log)
[recovery.log](https://github.com/user-attachments/files/16574191/recovery.log)

**Comment by bigbiff** [comment]
TWRP treats all partitions in the super partition as read only, following the defaults from AOSP.
