### ISSUE TITLE
Download impossible

### ISSUE THREAD

**Issue by Michas0206** [TeamWin/android_bootable_recovery#44]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices

**Device codename**: Galaxy S5 Klte
**TWRP version**: several, 3.4.0

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Just try to download (with latest Firefox or L-Os Browser) from mobile.

Just does not work (Standardbrowser) or stop after a few kb (Ff). Tried several times, cleaned cookies, switched from Eu to Us-server, switched to another mobile....no success.

Please give us better/working mirrors.

**Comment by bigbiff** [comment]
Make sure you have referrer turned on and try another browser.

**Comment by Michas0206** [comment]
Referrer should be on, 2 different browsers on one mobile and additionally tried a completely different mobile of my girlfriend. Unmodified browsers without addons etc

On my pc with Chromium everything is fine...but not on 2 mobiles here, whyever

**Comment by bigbiff** [comment]
It works fine from my computer in the US using Firefox on Windows 10.

**Comment by beacon1096** [comment]
I'm using Galaxy S5 (kltechn), and I think I ran into a similar situation.
https://dl.twrp.me/kltechn/twrp-3.4.0-0-kltechn.img.tar.html
https://dl.twrp.me/kltechn/twrp-3.4.0-0-kltechn.img.html
https://dl.twrp.me/kltechn/twrp-3.3.1-0-kltechn.img.tar.html
https://dl.twrp.me/kltechn/twrp-3.3.1-0-kltechn.img.html
On those pages (for example the first one), when I initiate the download, I got a twrp-3.4.0-0-kltechn.img.tar which is only about 7KB in size, and after I open it with vscode, I can see it's only a html document which seems to be https://dl.twrp.me/kltechn/twrp-3.4.0-0-kltechn.img.tar.html itself.
I have tried both in China and in Japan (on a vultr VPS), and I have tried some older versions, but the results are the same.

**Comment by beacon1096** [comment]
Oops. aria and firefox not working, but I got the file after using Internet Explorer.

**Comment by bigbiff** [comment]
If referrer isn't being set by the browser, the download will not work.
