### ISSUE TITLE
Nandroid Backup - Process createTarFork() ended with failure: 255

### ISSUE THREAD

**Issue by cmonty14** [TeamWin/android_bootable_recovery#6]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: dumpling
**TWRP version**: 3.3.1

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
I'm running in this failure when creating a nandroid backup.

#### WHAT IS THE EXPECTED RESULT?
Nandroid backup finishes w/o error.

#### WHAT HAPPENS INSTEAD?
Error message in app: `Process Process createTarFork() ended with failure: 255`
Error in recovery.log: `I:Error adding file '/data/user/10' to '/data/media/0/TWRP/BACKUPS/b94a5888/2020-01-25--15-53-15/data.ext4.win003'`

#### ADDITIONAL INFORMATION
For reference I have attached a screenshot of the app and the logfiles _recovery.log / dmesg.log

![Screenshot_2020-01-18-10-54-59_1_](https://user-images.githubusercontent.com/12523591/76620434-6de6d700-652d-11ea-8535-e70bc8601c4b.png)
[twrp_log.zip](https://github.com/TeamWin/android_bootable_recovery/files/4329491/twrp_log.zip)

**Comment by brigudav** [comment]
The problem is very old and cannot be solved. Try to remove multiusers with a crutch.
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1373#issuecomment-568148330

**Comment by bigbiff** [comment]
This is solved by using 3.4 and creating a new backup to use the new multi-user feature.
