### ISSUE TITLE
Why does 'fastboot boot twrp.img' not work?

### ISSUE THREAD

**Issue by ghost** [TeamWin/android_bootable_recovery#8]
I have to press Vol+ and Power to boot into the twrp recovery, otherwise it will boot into system.
What I want to do is to poweroff the device without booting the host system.

**Comment by ghost** [comment]
#7

**Comment by mauronofrio** [comment]
Which twrp?

**Comment by mauronofrio** [comment]
In the latest Xiaomi devices fastboot boot command is locked in the kernel, so you have to patch the kernel

**Comment by addhaloka** [comment]
> In the latest Xiaomi devices fastboot boot command is locked in the kernel, so you have to patch the kernel

What kernel? bootloader?

**Comment by ghost** [comment]
What kernel? bootloader?

**Comment by bigbiff** [comment]
Please open a more clear issue that is reproducible.
