### ISSUE TITLE
Xiaomi recovery returns always! i follow all the steps!! HELP

### ISSUE THREAD

**Issue by JMDTol** [TeamWin/android_bootable_recovery#80]
- [x ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ x] I am running the latest version of TWRP
- [ x] I have read the FAQ (https://twrp.me/FAQ/)
- [ x] I have searched for my issue and it does not already exist

**Device codename**: Redmi Note 7 "lavander"
**TWRP version**: twrp-3.4.0-0-lavender 

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
Im trying to install twrp in redmi note 7 lavander. 

I am following all the steps, even considering the final note https://twrp.me/xiaomi/xiaomiredminote7.html

After installing I always manage to enter the recovery, restart vol+ and power and i can enter to twrp, while I don't turn on the phone, but once I turn on the phone and the system, if I turn off the phone and try to enter the recovery again, the original xiaomi recovery returns.

I'm desperate, what can I do? please help!

Thanks!

Sorry for my english

#### ADDITIONAL INFORMATION
miui global 11.0.1 estable - 11.0.1.0(QFGEUXM)

**Comment by diassynthesis** [comment]
I encountered the same problem with my Redmi Note 8 Pro.
Try using this command before flashing TWRP Recovery:
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
After this step you can flash TWRP:
fastboot flash recovery twrp.img
fastboot reboot (And pressing the Vol+ button until the TWRP Logo appears for the second time).
Sorry for my bad english.

You can find the vbmeta.img file by uncompressing the Redmi Note 7 stock firmware, just copy it to the ADB folder

**Comment by diassynthesis** [comment]
Here is a complete guide to disable dm-verity: https://forum.hovatek.com/thread-32719.html
There is also another method to do it from TWRP: find and download the Disable_Dm-Verity_ForceEncrypt.zip and install it using TWRP install option. 

But i think that the best method is the first one: fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img

**Comment by diassynthesis** [comment]
To read and see if it can help.
https://miui.blog/any-devices/dm-verity-opt-encrypt-force-encryption-disabler-xiaomi/
https://www.getdroidtips.com/download-dm-verity-forced-encryption-disabler/
https://www.androidinfotech.com/no-verity-opt-encrypt-versions/

**Comment by JMDTol** [comment]
can i use the original file "vbmeta.img" from stock rom? or is it necessary to modify it? thanks!!!

**Comment by diassynthesis** [comment]
Yes, you can use it

**Comment by JMDTol** [comment]
yes! perfect!! it works!!

thanks!!!!

**Comment by diassynthesis** [comment]
Good news and good luck
