### ISSUE TITLE
Android 11 Support - Data Decryption

### ISSUE THREAD

**Issue by wSedlacek** [TeamWin/android_bootable_recovery#93]
- [ ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: umi
**TWRP version**: 3.4.0-11.0-1109

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
- Install an Android 11 ROM (in my case the latest MIUI EU build for Umi)
- Attempt to boot TWPR

#### WHAT IS THE EXPECTED RESULT?
- A prompt for my gesture or password is expected to be seen and the `/data` partition is expected to be decrypted after entering the correct password/passcode

#### WHAT HAPPENS INSTEAD?
- The `/data` partition will not prompt to decrypt and the following error will show in the log
```
Failed to mount '/data' (Invalid argument)
``` 

#### ADDITIONAL INFORMATION
I am currently running an unofficial fork, namely this [repo](https://github.com/LittleTurtle2333/android_device_xiaomi_umi-twrp). However as sited in [Xiaomi Mi 10 UMI - Internal storage decrypt does not work. #6](https://github.com/LittleTurtle2333/android_device_xiaomi_umi-twrp/issues/6) this appears to be an issue that extend beyond just this fork.

I understand no official Android 11 release has been made, however there doesn't appear to be any place that is tracking Android 11 issues, progress etc. So I wanted to create this issue so it could be tracked openly in the spirit of open source.

I am sure there are other issues that go beyond this for Android 11, but the Data Decryption is the biggest one that is affecting me. Perhaps others can chime in if they have tried to run TWRP on Android 11 and we can track those issues as well?

**Comment by mauronofrio** [comment]
Have you read somewhere TWRP is supporting android 11?

**Comment by wSedlacek** [comment]
> Have you read somewhere TWRP is supporting android 11?

It has been very difficult to find much information on what TWRP does and does not support and what the issues are.
I understand that that each device will have it's own maintainer and TWRP can't be responsible for the issues of every fork.
That being said I do believe it is important to track issues, even if they purely to understand what the limitations are.
I think a very good example of how issues done right is [Prisma](https://github.com/prisma/prisma/issues).

I really am just trying to help surface information for those looking for it.
I understand this is something that is likely already being worked on with no ETA.

**Comment by despicere** [comment]
Pls, add support android 11. twrp-3.4/5.0-9_lavender does not save settings (language, time zone)...
